name: Save Date

on:
  repository_dispatch:

jobs:
  append-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract date from client_payload and save into log file
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p _includes
          echo "${{ github.event.client_payload.line }}" >> _includes/dates.log

      - name: Inject public-safe env values
        run: |
          echo "<script>window.ENV = {" > _includes/env.js
          echo "ORG: '${{ secrets.PUBLIC_ORG }}'," >> _includes/env.js
          echo "REPO: '${{ secrets.PUBLIC_REPO }}'" >> _includes/env.js
          echo "};</script>" >> _includes/env.js

      - name: Commit and push changes
        run: |
          git add _includes/dates.log
          git commit -m "Append line \"${{ github.event.client_payload.line }}\""
          git push
